version: '3'
services:
  playground-web-db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: notetaking-app
    ports:
      - 27017:27017
  playground-web-frontend:
    image: playbackground-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://playground-web-backend:5000/
    ports:
      - 3000:80
  playground-web-backend:
    image: playground-web-backend:latest
    environment:
      MONGODB_URI: mongodb://playground-web-db:27017/notetaking-app
    ports:
      - 5000:5000