version: '3'
services:
  notetaking-frontend:
    image: notetaking-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://notetaking-backend:5000/
    ports:
      - 3000:80
  notetaking-backend:
    image: notetaking-backend:latest
    environment:
      MONGODB_URI: mongodb+srv://nghiadoan369:WoW121315@database-app.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
    ports:
      - 5000:5000