version: '3'
services:
  notetaking-frontend:
    image: notetaking-frontend:latest
    environment:
      PORT: 3000
      PROXY_API: http://notetaking-backend:5000/
    ports:
      - 3000:80
    volumes:
      - shared-images:/app/public/uploads
  notetaking-backend:
    image: notetaking-backend:latest
    environment:
      IMAGE_UPLOAD_PATH: /app/public/uploads
      MONGODB_URI: mongodb+srv://nghiadoan369:WoW121315@database-app.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
      PORT: 5000
      TOKEN_SECRET: 8e691d271cc8f180f66b11477359444cffdd8a074e63fc4a73c3a8e583970801e167b76cf54ddbdb2273422e7e4e9ae77ad2be31cc415bd00d968a1031b3b029
      JWT_EXPIRATION: 5h
    ports:
      - 5000:5000
    volumes:
      - shared-images:/app/public/uploads

volumes:
  shared-images: